name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Docker script
      uses: WorkplaceX/Research/GitHubActions/Docker@master
      with:
        myparam: 'MyParamy'
    - uses: actions/checkout@v1
    - name: Install script
      env: 
        My: ${{ secrets.My }} 
      run: ./GitHubActions/install.sh
    - name: Build script
      run: ./GitHubActions/build.sh
    - name: Arti
      uses: actions/upload-artifact@v2
      with:
        name: artifact-readme
        path: README.md
    
