name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install script
      env: 
        My: ${{ secrets.My }} 
      run: ./"GitHub Actions"/install.sh
    - name: Build script
      run: ./"GitHub Actions"/build.sh
    - name: Docker script
      runs:
        using 'docker'
        image: './"GitHub Actions"/Docker/Dockerfile'
