name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Docker script
      run:
        using: 'docker'
        image: 'Dockerfile'      
    - name: Install script
      env: 
        My: ${{ secrets.My }} 
      run: ./GitHubActions/install.sh
    - name: Build script
      run: ./GitHubActions/build.sh
