name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install script
      env: 
        My: ${{ secrets.My }} 
      run: ./GitHubActions/install.sh
      run: ./GitHubActions/Docker/Dockerfile
    - name: Build script
      run: ./GitHubActions/build.sh
