name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Docker script
    - name: Install script
      env: 
        My: ${{ secrets.My }} 
      run: ./GitHubActions/install.sh
    - name: Build script
      run: ./GitHubActions/build.sh
